- name: Ensure IP forward bit is activated
  sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes

- name: Ensure IPv4 rp filter is deactivated
  sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present reload=yes

- name: Ensure IPv4 default rp filter is deactivated
  sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present reload=yes

- name: Install neutron on network node (Be patient)
  apt:
    name={{ item }}
    state=latest
  with_items:
#    - neutron-linuxbridge-agent
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-plugin-ml2


- name: Setup neutron.conf on network
  template: >
    src=../neutron_controller/templates/etc/neutron/neutron.conf
    dest=/etc/neutron/neutron.conf
    owner=root
    group=root
    mode=0644

#- name: Setup ml2_conf.ini on network
#  template: >
#    src=etc/neutron/plugins/ml2/ml2_conf.ini
#    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
#    owner=root
#    group=root
#    mode=0644

- name: Setup l3_agent.ini on network
  template: >
    src=etc/neutron/l3_agent.ini
    dest=/etc/neutron/l3_agent.ini
    owner=root
    group=root
    mode=0644
  notify:
    - restart neutron-l3-agent

- name: Setup dhcp_agent.ini on network
  template: >
    src=etc/neutron/dhcp_agent.ini
    dest=/etc/neutron/dhcp_agent.ini
    owner=root
    group=root
    mode=0644
  notify:
    - restart neutron-dhcp-agent

- name: Setup dnsmasq-neutron.conf on network
  template: >
    src=etc/neutron/dnsmasq-neutron.conf
    dest=/etc/neutron/dnsmasq-neutron.conf
    owner=root
    group=root
    mode=0644

- name: Setup metadata_agent.ini on network
  template: >
    src=etc/neutron/metadata_agent.ini
    dest=/etc/neutron/metadata_agent.ini
    owner=root
    group=root
    mode=0644
  notify:
    - restart neutron-metadata-agent

- name: Setup openvswitch.ini on network
  template: >
    src=etc/neutron/plugins/ml2/openvswitch_agent.ini
    dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
    owner=root
    group=root
    mode=0644
  notify:
    - restart neutron-openvswitch-agent
    
- name: Restart openvswitch-switch service
  service: name=openvswitch-switch state=restarted

#- name: Add the external bridge
#  command: ovs-vsctl add-br br-ex

#- name: Add port to external bridge
#  command: ovs-vsctl add-port br-ex {{ tunnel_interface }}

