- hosts: compute
  become: true
  tasks:
    - name: Delete /etc/neutron/plugins/ml2/openvswitch_agent.ini
      command: rm /etc/neutron/plugins/ml2/openvswitch_agent.ini
      ignore_errors: yes

    - name: Delete /etc/neutron/plugins/ml2/ml2_conf.ini
      command: rm /etc/neutron/plugins/ml2/ml2_conf.ini
      ignore_errors: yes

    - name: Delete /etc/neutron/neutron.conf
      command: rm /etc/neutron/neutron.conf
      ignore_errors: yes

- hosts: network
  become: true
  tasks:
    - name: Delete /etc/neutron/plugins/ml2/openvswitch_agent.ini
      command: rm /etc/neutron/plugins/ml2/openvswitch_agent.ini
      ignore_errors: yes

    - name: Delete /etc/neutron/metadata_agent.ini
      command: rm /etc/neutron/metadata_agent.ini
      ignore_errors: yes

    - name: Delete /etc/neutron/dnsmasq-neutron.conf
      command: rm /etc/neutron/dnsmasq-neutron.conf
      ignore_errors: yes

    - name: Delete /etc/neutron/dhcp_agent.ini
      command: rm /etc/neutron/dhcp_agent.ini
      ignore_errors: yes

    - name: Delete /etc/neutron/l3_agent.ini
      command: rm /etc/neutron/l3_agent.ini
      ignore_errors: yes

    - name: Delete /etc/neutron/neutron.conf
      command: rm /etc/neutron/neutron.conf
      ignore_errors: yes

- hosts: controller
  become: true
  tasks:
    - name: Delete /etc/neutron/plugins/ml2/ml2_conf.ini
      command: rm /etc/neutron/plugins/ml2/ml2_conf.ini
      ignore_errors: yes

    - name: Delete /etc/neutron/neutron.conf
      command: rm /etc/neutron/neutron.conf
      ignore_errors: yes

    - name: Drop neutron database
      mysql_db:
        name: neutron
        state: absent

