- hosts: all
  become: true
  roles:
    - basic

- hosts: controller
  become: true
  roles:
    - controller_interface

- hosts: compute, object
  become: true
  roles:
    - compute_interface

- hosts: block
  become: true
  roles:
    - block_interface

- hosts: all
  become: true
  tasks:
    - debug:
        msg: "Servers are going to be rebooted. Wait a moment and continue with the second playbook"

    - name: Restart
      shell: reboot
      async: 0
      poll: 0

#    - name: Wait for the server to finish rebooting
#      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=120
