- hosts: controller
  become: true
  roles:
    - ntp_server

- hosts: compute
  become: true
  roles:
    - ntp_others

- hosts: all
  become: true
  roles:
    - openstack_packages

- hosts: controller
  become: true
  roles:
    - sql_database
    - rabbitmq
    - memcached
    - keystone_controller
    - keystone_setup
    - glance_controller
    
