- hosts: controller
  become: true
  roles:
    - ntp_server

- hosts: compute, block
  become: true
  roles:
    - ntp_others

- hosts: all
  become: true
  roles:
    - openstack_packages

- hosts: controller
  become: true
  roles:
    - sql_database
    - rabbitmq
    - memcached
    - keystone_controller
    - keystone_setup
    - glance_controller
    - nova_controller

- hosts: compute
  become: true
  roles:
    - nova_compute

- hosts: controller
  become: true
  roles:
    - nova_flavor
    - nova_host_discovery
    - neutron_controller

- hosts: compute
  become: true
  roles:
    - neutron_compute

- hosts: controller
  become: true
  roles:
    - horizon
    - image_upload
    - network_setup
    - cinder_controller

- hosts: block
  become: true
  roles:
    - cinder_storage

- hosts: controller
  become: true
  roles:
    - heat

#- hosts: compute
#  become: true
#  roles:
#    - ceilometer_compute

- hosts: controller
  become: true
  roles:
#    - ceilometer_controller
    - barbican
