- hosts: all
  become: true
  roles:
    - basic

- hosts: all
  become: true
  roles:
    - management_tunnel_interfaces

- hosts: controller, network
  become: true
  roles:
    - provider_interface

- hosts: all
  become: true
  tasks:
    - debug:
        msg: "Servers are going to be rebooted. Wait a moment and continue with the second playbook"

    - name: Restart
      shell: reboot
      async: 0
      poll: 0
