- name: Create magnum database
  mysql_db:
    name: magnum
    state: present

- name: Granting access to magnum database
  mysql_user: >
    name=magnum
    host={{ item }}
    password={{ magnum_dbpass }}
    priv=magnum.*:ALL
    append_privs=yes
  with_items:
    - "{{ controller_management_ip }}"
    - "127.0.0.1"
    - "localhost"
    - "::1"
    - "%"

- name: Create magnum user
  os_user:
    cloud=lowcost
    state=present
    name=magnum
    password={{magnum_dbpass}}
    domain=default

- name: Grant the admin role on the user magnum in the project service
  os_user_role:
    cloud: lowcost
    user: magnum
    role: admin
    project: service

- name: Create a service for magnum
  os_keystone_service:
    cloud: lowcost
    state: present
    name: magnum
    service_type: container-infra
    description: OpenStack Container Infrastructure Management Service

- name: Create container-infra public service API endpoint with keystone_service
  shell: openstack --os-cloud=lowcost endpoint create --region {{region}} container-infra public http://{{short_controller_name}}:9511/v1

- name: Create container-infra internal service API endpoint with keystone_service
  shell: openstack --os-cloud=lowcost endpoint create --region {{region}} container-infra internal http://{{short_controller_name}}:9511/v1

- name: Create container-infra admin service API endpoint with keystone_service
  shell: openstack --os-cloud=lowcost endpoint create --region {{region}} container-infra admin http://{{short_controller_name}}:9511/v1

- name: Create the magnum domain
  os_keystone_domain:
     cloud: lowcost
     state: present
     name: magnum
     description: Owns users and projects created by magnum

- name: Create magnum_domain_admin user in the magnum domain
  os_user:
    cloud=lowcost
    state=present
    name=magnum_domain_admin
    password={{magnum_dbpass}}
    domain=magnum

- name: Add the admin role to the magnum_domain_admin user in the magnum domain by the magnum_domain_admin user
  command: openstack --os-cloud=lowcost role add --domain magnum --user-domain magnum --user magnum_domain_admin admin

- name: Install magnum (Be patient)
  apt:
    name={{ item }}
    state=latest
  with_items:
    - magnum-api
    - magnum-conductor
    - python-magnumclient

- name: Setup magnum.conf on controller
  template: >
    src=etc/magnum/magnum.conf
    dest=/etc/magnum/magnum.conf
    owner=root
    group=root
    mode=0644

- name: Build magnum database (Be patient)
  command: 'su -s /bin/sh -c "magnum-db-manage upgrade" magnum'
  notify:
    - restart magnum-api
    - restart magnum-conductor
