- name: Instalar componentes de base de datos (mariadb-server, python-pymysql)
  apt:
    name={{ item }}
  with_items:
    - mariadb-server
    - python-pymysql
    - libmysqlclient-dev

- name: Configurar 99-openstack.cnf en controller
  template: >
    src=etc/mysql/mariadb.conf.d/99-openstack.cnf
    dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner=root
    group=root
    mode=0644
  notify: restart mysql

- name: Install the Python MySQLB module
  pip: name=MySQL-python

  # Set root password
# UPDATE mysql.user SET Password=PASSWORD('mysecret') WHERE User='root';
# FLUSH PRIVILEGES;

- name: Set root Password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Add .my.cnf
  template: >
    src=root/my.cnf
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600

- name: Remove anonymous users
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - "{{ controller_management_ip }}"
    - 127.0.0.1
    - ::1

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
