- name: Install database components (mariadb-server, python-pymysql)
  apt:
    name={{ item }}
  with_items:
    - mariadb-server
    - python-pymysql
    - libmysqlclient-dev

- name: Setup 99-openstack.cnf on controller
  template: >
    src=etc/mysql/mariadb.conf.d/99-openstack.cnf
    dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner=root
    group=root
    mode=0644

- name: restart mysql
  service: name=mysql state=restarted

- name: Install the Python MySQLB module
  pip: name=MySQL-python

- name: Update mysql root password for all root accounts
  mysql_user: >
    name=root
    host=localhost
    password={{ mysql_root_password }}

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Add .my.cnf
  template: >
    src=root/my.cnf
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600

- name: restart mysql
  service: name=mysql state=restarted

- name: Update mysql root password for all root accounts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
  with_items:
    - "{{ nodes.controller.management_ip }}"
    - localhost
    - 127.0.0.1

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - "{{ nodes.controller.management_ip }}"
    - 127.0.0.1
    - ::1
