- name: Instalar componentes de base de datos (mariadb-server, python-pymysql)
  apt:
    name={{ item }}
  with_items:
    - mariadb-server
    - python-pymysql
    - libmysqlclient-dev

- name: Configurar 99-openstack.cnf en controller
  template: >
    src=etc/mysql/mariadb.conf.d/99-openstack.cnf
    dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner=root
    group=root
    mode=0644
  notify:
    - restart mysql

- name: Install the Python MySQLB module
  pip: name=MySQL-python

- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host=localhost
    password={{ mysql_root_password }}

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Add .my.cnf
  template: >
    src=root/my.cnf
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600
  notify:
    - restart mysql

- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
  with_items:
    - "{{ controller_management_ip }}"
    - localhost
    - 127.0.0.1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - "{{ controller_management_ip }}"
    - 127.0.0.1
    - ::1
