- name: Install nova on compute nodes (Be patient)
  apt:
    name: nova-compute
    state: latest

- name: Setup nova.conf on compute
  template: >
    src=etc/nova/nova.conf
    dest=/etc/nova/nova.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart nova-compute
