- name: Create keystone database
  mysql_db:
    name: keystone
    state: present

- name: Granting access to keystone database
  mysql_user: >
    name=keystone
    host={{ item }}
    password={{ keystone_dbpass }}
    priv=keystone.*:ALL
    append_privs=yes
  with_items:
    - "{{ nodes.controller.management_ip }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
    - "%"

- name: Install keystone packages (Be patient)
  apt:
    name={{ item }}
    state=latest
  with_items:
    - keystone
    - apache2 
    - libapache2-mod-wsgi

- name: Setup keystone.conf on controller
  template: >
    src=etc/keystone/keystone.conf
    dest=/etc/keystone/keystone.conf
    owner=root
    group=root
    mode=0644

- name: restart mysql
  service: name=mysql state=restarted

- name: Build keystone database (Be patient)
  command: 'su -s /bin/sh -c "keystone-manage db_sync" keystone'

- name: Initialize Fernet key repositories (1/2)
  command: 'keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone'

- name: Initialize Fernet key repositories (2/2)
  command: 'keystone-manage credential_setup --keystone-user keystone --keystone-group keystone'

- name: Bootstrap the Identity service
  command: 'keystone-manage bootstrap --bootstrap-password {{ admin_pass}} --bootstrap-admin-url http://{{ nodes.controller.name }}:35357/v3/ --bootstrap-internal-url http://{{ nodes.controller.name }}:5000/v3/ --bootstrap-public-url http://{{ nodes.controller.management_ip }}:5000/v3/ --bootstrap-region-id {{ region }}'

- name: Setup apache2.conf on controller
  template: >
    src=etc/apache2/apache2.conf
    dest=/etc/apache2/apache2.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart apache

- name: Remove the default SQLite database
  file:
    state=absent
    path='/var/lib/keystone/keystone.db'

- name: Setup openrc-admin for root user on controller
  template: >
    src=root/openrc-admin
    dest=/root/openrc-admin
    owner=root
    group=root
    mode=0600

- name: Setup openrc-demo for root user on controller
  template: >
    src=root/openrc-demo
    dest=/root/openrc-demo
    owner=root
    group=root
    mode=0600

- name: Install the Python os_project module
  pip: name=shade
