- name: restart ceilometer-agent-central
  service: name=ceilometer-agent-central state=restarted

- name: restart ceilometer-agent-notification
  service: name=ceilometer-agent-notification state=restarted

- name: restart ceilometer-collector
  service: name=ceilometer-collector state=restarted
  
