- name: "Update package cache"
  apt:
    update_cache: yes

- name: "Update packages (Be patient)"
  apt:
    upgrade: dist

- name: "Adding openstack host names to /etc/hosts"
  blockinfile:
    name: /etc/hosts
    block: |
      # Controller
      {{controller_management_ip}} controller

      # Compute
      {{compute01_management_ip}} compute01

      # Block storage
      {{block_management_ip}} block

- name: "Install pip"
  apt:
    name: python-pip

- name: "Update pip"
  pip:
    name: pip
    extra_args: --upgrade
