- name: "Update package cache"
  apt:
    update_cache: yes

- name: "Update packages (Be patient)"
  apt:
    upgrade: dist

- name: "Adding openstack controller, network and block host names to /etc/hosts"
  blockinfile:
    name: /etc/hosts
    block: |
      # Controller
      {{nodes.controller.management_ip}} {{nodes.controller.name}}

      # Network node
      {{nodes.network.management_ip}} {{nodes.network.name}}

      # Block storage
      {{nodes.block.management_ip}} {{nodes.block.name}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK controller, network  and block nodes"


- name: "Adding openstack compute node names to /etc/hosts"
  blockinfile:
    name: /etc/hosts
    block: |
      {{item.management_ip}} {{item.name}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
      - "{{nodes.compute}}"

- name: "Adding openstack object node names to /etc/hosts"
  blockinfile:
    name: /etc/hosts
    block: |
      {{item.management_ip}} {{item.name}}

    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
      - "{{nodes.object}}"

- name: "Install pip"
  apt:
    name: python-pip

- name: "Update pip"
  pip:
    name: pip
    extra_args: --upgrade
