- name: Install Memcached (Be patient)
  apt:
    name={{ item }}
  with_items:
    - memcached
    - python-memcache

- name: Setup memcached.conf
  template: >
    src=etc/memcached.conf
    dest=/etc/memcached.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart memcached
