- name: Instalar Memcached
  apt:
    name={{ item }}
  with_items:
    - memcached
    - python-memcache

- name: Configurar memcached.conf
  template: >
    src=etc/memcached.conf
    dest=/etc/memcached.conf
    owner=root
    group=root
    mode=0644
  notify: restart memcached
