- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Install ubuntu-cloud-keyring
  apt:
    name: ubuntu-cloud-keyring
    state: latest

- name: Add OpenStack repository
  apt_repository:
    #repo: cloud-archive:ocata
    #De dónde han sacado iesgn lo siguiente?
    repo: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main"
    state: present
    update_cache: yes

- name: "Update packages"
  apt:
    upgrade: dist

- name: Install python-openstackclient
  apt:
    name: python-openstackclient
    state: latest
