- name: Download Cirros image
  get_url:
    url: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
    dest: /tmp/cirros-0.3.5-x86_64-disk.img

- name: Upload the Cirros image
  os_image:
    cloud: lowcost
    name: cirros
    container_format: bare
    disk_format: qcow2
    state: present
    is_public: true
    filename: /tmp/cirros-0.3.5-x86_64-disk.img
